name: Build and Update

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout v0.5.4 code
              uses: actions/checkout@v3
              with:
                  ref: v0.5.4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Set up Gradle
              uses: gradle/gradle-build-action@v2

            - name: Build the mod
              run: |
                  ./gradlew build || exit 1

            - name: List JAR files
              run: |
                  echo "Listing jar files in build/libs:"
                  ls build/libs/*.jar || exit 1

            - name: Get Release Upload URL
              id: get_release
              run: |
                  upload_url=$(curl -s \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    https://api.github.com/repos/${{ github.repository }}/releases/tags/v0.5.4 \
                    | jq -r .upload_url | sed -e "s/{?name,label}//")
                  if [ -z "$upload_url" ]; then
                    echo "Failed to get upload URL."
                    exit 1
                  fi
                  echo "::set-output name=upload_url::$upload_url"

            - name: Upload JAR - Main
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.get_release.outputs.upload_url }}
                  asset_path: build/libs/meteor-client-0.5.4.jar
                  asset_name: meteor-client-0.5.4.jar
                  asset_content_type: application/java-archive
